### ISSUE TITLE
Use increment_string()

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/CodeIgniter-Slug-Library#1]
Update this library to use the new increment_string() CodeIgniter function 
http://codeigniter.com/user_guide/helpers/string_helper.html

**Comment by n3gotium** [comment]
Hello. I've found some syntex error in your code. At line 186 you have this: 
$CI->db->where($this->id.'!=', $id);
and shoul be: 
$CI->db->where($this->id.' !=', $id);
You forgot to add a space before the exclamation mark. It throws an error because of that (at least in Codeignitor 2.2.0). Thanks.

**Comment by ericlbarnes** [comment]
Thanks. This was fixed in #3
