### ISSUE TITLE
Allow user specify custom slug

### ISSUE THREAD

**Issue by davirtavares** [ericlbarnes/CodeIgniter-Slug-Library#4]
I think users may specify a custom slug, sometimes (like on the projects I work on), users want to write their own slug and the Slug lib can just check and append de counter if it duplicates other records.

**Comment by ericlbarnes** [comment]
Probably best to fork this and add that to your copy. I haven't used this plugin in a few years now and not interested in changing the functionality.

**Comment by davirtavares** [comment]
Hey Eric, thanks for the feedback. Yes I'm going to fork Slug later and apply the modifications.
